project_name: rep

builds:
  - binary: rep

brews:
  - tap:
      owner: wyattjoh
      name: homebrew-stable
    folder: Formula
    homepage: https://github.com/wyattjoh/rep
    description: Javascript reproduction manager, written in Go
    test: |
      system "#{bin}/rep -v"
    install: |
      bin.install "rep"

archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE.md
      - README.md

release:
  github:
    owner: wyattjoh
    name: rep
