name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.18.3"
      - uses: golangci/golangci-lint-action@v3.3.0
        with:
          version: v1.46.2
      - name: Test Build
        run: go build .
